server:
  port: 8083

spring:
  web:
    cors:
      allowed-origins: http://localhost:5173
  application:
    name: authservice


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3307/auth-service-estimapoker?createDatabaseIfNotExist=true
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username:
    password:

queue:
  name: default.email

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true

api:
  security:
    token:
      secret:

resilience4j:
  ratelimiter:
    instances:
      authservice:
        limit-for-period: 5
        limit-refresh-period: 15s
        timeout-duration: 10s
        register-health-indicator: true
